version: 1.b{build}
skip_tags: true
skip_branch_with_pr: true
max_jobs: 2
image: Visual Studio 2017
init: 
  - git clone --recursive https://github.com/thpatch/thcrap.git C:\projects\thcrap
  - git clone https://github.com/3gstudent/signtools.git --depth 1 C:\projects\signtools
# platform: x86
configuration: Release
before_build: 
  - cd C:\projects\thcrap
# - openssl genrsa -out pvtPrivate.key 2048
  - ..\signtools\makecert -n "CN=AppVeyor CI,E=ci@appveyor.com" -$ individual -a sha256 -len 4096 -r -cy authority -sky signature -pe -sk . cert.cer
  - dir
  - ..\signtools\pvk2pfx -pvk cert.pvk -spc cert.cer -pfx cert.pfx
build_script:
  - cd C:\projects\thcrap
  - msbuild /m /p:Configuration=Release
after_build:
  - cd C:\projects\thcrap
  - 7z a -tzip .\thcrap.zip .\bin\*
artifacts:
  - path: ..\thcrap.zip
