version: 1.b{build}
skip_tags: true
skip_branch_with_pr: true
max_jobs: 2
image: Visual Studio 2013
init: 
  - |
    git clone --recursive https://github.com/thpatch/thcrap.git
    cd thcrap
    msbuild thcrap.sln /m /p:Configuration=Debug
    7z a -tzip .\thcrap.zip .\bin\*
artifacts:
  - path: thcrap\thcrap.zip
