version: 1.b{build}
skip_tags: true
skip_branch_with_pr: true
max_jobs: 2
image: Visual Studio 2017
init: 
  - git clone --recursive https://github.com/thpatch/thcrap.git C:\projects\thcrap
# platform: x86
configuration: Release
build:
  parallel: true
  project: C:\projects\thcrap\thcrap.sln
  verbosity: minimal
after_build:
  - cd C:\projects\thcrap
  - 7z a -tzip .\thcrap.zip .\bin\*
artifacts:
  - path: C:\projects\thcrap\thcrap.zip
