version: 1.b{build}
skip_tags: true
skip_branch_with_pr: true
max_jobs: 2
image: Visual Studio 2017
init: 
  - git clone --recursive https://github.com/thpatch/thcrap.git C:\projects\thcrap
# platform: x86
configuration: Release
before_build: 
  - C:\"Program Files (x86)"\"Microsoft Visual Studio"\2017\Community\VC\Auxiliary\Build\vcvarsall.bat x64
  - cd C:\projects\thcrap
  - makecert -n "CN=AppVeyor CI,E=ci@appveyor.com" -$ individual -a sha256 -len 4096 -r -cy authority -sky signature -pe -sv cert.pvk cert.cer
  - pvk2pfx -pvk cert.pvk -spc cert.cer -pfx cert.pfx
build:
  project: C:\projects\thcrap\thcrap.sln
  verbosity: minimal
after_build:
  - cd C:\projects\thcrap
  - 7z a -tzip .\thcrap.zip .\bin\*
artifacts:
  - path: C:\projects\thcrap\thcrap.zip
